name       : ruby-redcarpet
version    : 3.4.0
release    : 1
source     :
    - https://rubygems.org/downloads/redcarpet-3.4.0.gem : a7b10a67a2c11d7a1945caa7fbfc2e6c8fcbe4583ff355af9d499319a1f83841
license    : MIT
component  : programming.perl
summary    :  Fast, safe and extensible Markdown to (X)HTML parser.
description: |
     Fast, safe and extensible Markdown to (X)HTML parser.
extract    : no
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - ruby
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/redcarpet-$version.gem
