name       : ruby-redcarpet
version    : 3.5.0
release    : 6
source     :
    - https://rubygems.org/downloads/redcarpet-3.5.0.gem : f3d445d6f573fcb33d9e7cdaa602434b88f10cc5a37e7133d0b52c0443f76c6a
license    : MIT
component  : programming.ruby
summary    : Fast, safe and extensible Markdown to (X)HTML parser.
description: |
    Fast, safe and extensible Markdown to (X)HTML parser.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc}
