name       : ruby-redcarpet
version    : 3.5.1
release    : 7
source     :
    - https://rubygems.org/downloads/redcarpet-3.5.1.gem : 717f64cb6ec11c8d9ec9b521ed26ca2eeda68b4fe1fc3388a641176dbd47732f
homepage   : https://rubygems.org/gems/redcarpet
license    : MIT
component  : programming.ruby
summary    : Fast, safe and extensible Markdown to (X)HTML parser
description: |
    Fast, safe and extensible Markdown to (X)HTML parser.
builddeps  :
    - pkgconfig(ruby-3.1)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc}
